import { prisma } from "../src/config/prismaClient.config";

// command --> npx prisma db seed

const organizerProfiles = [
  {
    userId: "fb06b4f3-304d-4dad-9046-b85ff64bc02f",
    name: "Purwadhika",
  },
];

async function main() {
  await prisma.organizerProfile.createMany({ data: organizerProfiles });
}

main()
  .then(() => console.log("success"))
  .catch((e) => console.log(e))
  .finally(async () => {
    await prisma.$disconnect();
  });

//   const events = [
//   {
//     organizerId: "b85a52ee-2310-4018-a3e8-48b748ec2915",
//     userId: "fb06b4f3-304d-4dad-9046-b85ff64bc02f",

//     title: "Jakarta Tech Conference 2026",
//     slug: "jakarta-tech-conference-2026",
//     description:
//       "Konferensi teknologi terbesar untuk developer, startup, dan tech enthusiasts.",
//     availableSlot: 300,

//     locationName: "Jakarta Convention Center",
//     address: "Jl. Gatot Subroto No.1, Jakarta",
//     city: "Jakarta",

//     eventDate: "2026-09-15T09:00:00Z",
//     startSellingDate: "2026-06-01T00:00:00Z",
//     endSellingDate: "2026-09-14T23:59:00Z",

//     isFree: false,
//     price: 250000,
//   },
// ];

//   const eventCoupons = [
//   {
//     couponCode: "MOVIEFEST22",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "75775fab-d486-4d5e-977c-5985586466d2",
//     validFrom: new Date("2026-06-15T00:00:00.000Z"),
//     validUntil: new Date("2026-06-30T00:00:00.000Z"),
//     discountAmount: 22,
//   },
//   {
//     couponCode: "FOODFEST10",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "59c758f8-3d1d-4ccc-9ad2-40826f990283",
//     validFrom: new Date("2026-03-05T00:00:00.000Z"),
//     validUntil: new Date("2026-03-18T00:00:00.000Z"),
//     discountAmount: 10,
//   },
//   {
//     couponCode: "EDUFAIR25",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "4ef325cc-6f24-432e-b409-e914737285a3",
//     validFrom: new Date("2026-10-01T00:00:00.000Z"),
//     validUntil: new Date("2026-10-20T00:00:00.000Z"),
//     discountAmount: 25,
//   },
//   {
//     couponCode: "GADGETSALE12",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "45d54fe6-c699-4225-85db-6c1dabc9e0ee",
//     validFrom: new Date("2026-05-01T00:00:00.000Z"),
//     validUntil: new Date("2026-05-15T00:00:00.000Z"),
//     discountAmount: 12,
//   },
//   {
//     couponCode: "DESIGNWEEK18",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "441b55fd-122f-46b3-9ba0-fa4d670bd263",
//     validFrom: new Date("2026-07-05T00:00:00.000Z"),
//     validUntil: new Date("2026-07-18T00:00:00.000Z"),
//     discountAmount: 18,
//   },
//   {
//     couponCode: "AUTOEXPO30",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "2c767a42-5d6e-481e-ab4d-9b01225d063a",
//     validFrom: new Date("2026-09-15T00:00:00.000Z"),
//     validUntil: new Date("2026-09-30T00:00:00.000Z"),
//     discountAmount: 30,
//   },
//   {
//     couponCode: "TRAVELFAIR7",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "2bb73656-0da1-4b19-ac25-92441bad7369",
//     validFrom: new Date("2026-04-01T00:00:00.000Z"),
//     validUntil: new Date("2026-04-12T00:00:00.000Z"),
//     discountAmount: 7,
//   },
//   {
//     couponCode: "PETSHOW10",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "1d21e5ab-ff38-4fda-b03a-f3f86dfb8298",
//     validFrom: new Date("2026-03-12T00:00:00.000Z"),
//     validUntil: new Date("2026-03-25T00:00:00.000Z"),
//     discountAmount: 10,
//   },
//   {
//     couponCode: "GREENEXPO12",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "1b933500-dc5b-43b6-8e19-dcbfb8c48064",
//     validFrom: new Date("2026-05-20T00:00:00.000Z"),
//     validUntil: new Date("2026-05-30T00:00:00.000Z"),
//     discountAmount: 12,
//   },
//   {
//     couponCode: "CHARITY5",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "1a5e46f2-2401-4947-bc33-ac46643e3587",
//     validFrom: new Date("2026-02-01T00:00:00.000Z"),
//     validUntil: new Date("2026-02-12T00:00:00.000Z"),
//     discountAmount: 5,
//   },
//   {
//     couponCode: "FINTECH15",
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     eventId: "0b1f6b14-4cdc-4249-9eb6-57a817636454",
//     validFrom: new Date("2026-08-10T00:00:00.000Z"),
//     validUntil: new Date("2026-08-25T00:00:00.000Z"),
//     discountAmount: 15,
//   },
// ];

// ------- ORGANIZER PROFILES
//   const organizerProfiles = [
//   {
//     userId: "678272fb-af57-429b-8e41-4eb78e541c05",
//     name: "Purwadhika School",
//     image: "https://picsum.photos/seed/event1/600/400",
//   },
// ];

// ------- COUNTRIES
// const countries = [
//   { countryName: "Afghanistan", countryCode: "AF" },
//   { countryName: "Albania", countryCode: "AL" },
//   { countryName: "Algeria", countryCode: "DZ" },
//   { countryName: "Andorra", countryCode: "AD" },
//   { countryName: "Angola", countryCode: "AO" },
//   { countryName: "Antigua and Barbuda", countryCode: "AG" },
//   { countryName: "Argentina", countryCode: "AR" },
//   { countryName: "Armenia", countryCode: "AM" },
//   { countryName: "Australia", countryCode: "AU" },
//   { countryName: "Austria", countryCode: "AT" },
//   { countryName: "Azerbaijan", countryCode: "AZ" },
//   { countryName: "Bahamas", countryCode: "BS" },
//   { countryName: "Bahrain", countryCode: "BH" },
//   { countryName: "Bangladesh", countryCode: "BD" },
//   { countryName: "Barbados", countryCode: "BB" },
//   { countryName: "Belarus", countryCode: "BY" },
//   { countryName: "Belgium", countryCode: "BE" },
//   { countryName: "Belize", countryCode: "BZ" },
//   { countryName: "Benin", countryCode: "BJ" },
//   { countryName: "Bhutan", countryCode: "BT" },
//   { countryName: "Bolivia", countryCode: "BO" },
//   { countryName: "Bosnia and Herzegovina", countryCode: "BA" },
//   { countryName: "Botswana", countryCode: "BW" },
//   { countryName: "Brazil", countryCode: "BR" },
//   { countryName: "Brunei", countryCode: "BN" },
//   { countryName: "Bulgaria", countryCode: "BG" },
//   { countryName: "Burkina Faso", countryCode: "BF" },
//   { countryName: "Burundi", countryCode: "BI" },
//   { countryName: "Cabo Verde", countryCode: "CV" },
//   { countryName: "Cambodia", countryCode: "KH" },
//   { countryName: "Cameroon", countryCode: "CM" },
//   { countryName: "Canada", countryCode: "CA" },
//   { countryName: "Central African Republic", countryCode: "CF" },
//   { countryName: "Chad", countryCode: "TD" },
//   { countryName: "Chile", countryCode: "CL" },
//   { countryName: "China", countryCode: "CN" },
//   { countryName: "Colombia", countryCode: "CO" },
//   { countryName: "Comoros", countryCode: "KM" },
//   { countryName: "Congo", countryCode: "CG" },
//   { countryName: "Costa Rica", countryCode: "CR" },
//   { countryName: "Croatia", countryCode: "HR" },
//   { countryName: "Cuba", countryCode: "CU" },
//   { countryName: "Cyprus", countryCode: "CY" },
//   { countryName: "Czechia", countryCode: "CZ" },
//   { countryName: "Denmark", countryCode: "DK" },
//   { countryName: "Djibouti", countryCode: "DJ" },
//   { countryName: "Dominica", countryCode: "DM" },
//   { countryName: "Dominican Republic", countryCode: "DO" },
//   { countryName: "Ecuador", countryCode: "EC" },
//   { countryName: "Egypt", countryCode: "EG" },
//   { countryName: "El Salvador", countryCode: "SV" },
//   { countryName: "Equatorial Guinea", countryCode: "GQ" },
//   { countryName: "Eritrea", countryCode: "ER" },
//   { countryName: "Estonia", countryCode: "EE" },
//   { countryName: "Eswatini", countryCode: "SZ" },
//   { countryName: "Ethiopia", countryCode: "ET" },
//   { countryName: "Fiji", countryCode: "FJ" },
//   { countryName: "Finland", countryCode: "FI" },
//   { countryName: "France", countryCode: "FR" },
//   { countryName: "Gabon", countryCode: "GA" },
//   { countryName: "Gambia", countryCode: "GM" },
//   { countryName: "Georgia", countryCode: "GE" },
//   { countryName: "Germany", countryCode: "DE" },
//   { countryName: "Ghana", countryCode: "GH" },
//   { countryName: "Greece", countryCode: "GR" },
//   { countryName: "Grenada", countryCode: "GD" },
//   { countryName: "Guatemala", countryCode: "GT" },
//   { countryName: "Guinea", countryCode: "GN" },
//   { countryName: "Guyana", countryCode: "GY" },
//   { countryName: "Haiti", countryCode: "HT" },
//   { countryName: "Honduras", countryCode: "HN" },
//   { countryName: "Hungary", countryCode: "HU" },
//   { countryName: "Iceland", countryCode: "IS" },
//   { countryName: "India", countryCode: "IN" },
//   { countryName: "Indonesia", countryCode: "ID" },
//   { countryName: "Iran", countryCode: "IR" },
//   { countryName: "Iraq", countryCode: "IQ" },
//   { countryName: "Ireland", countryCode: "IE" },
//   { countryName: "Israel", countryCode: "IL" },
//   { countryName: "Italy", countryCode: "IT" },
//   { countryName: "Jamaica", countryCode: "JM" },
//   { countryName: "Japan", countryCode: "JP" },
//   { countryName: "Jordan", countryCode: "JO" },
//   { countryName: "Kazakhstan", countryCode: "KZ" },
//   { countryName: "Kenya", countryCode: "KE" },
//   { countryName: "Kiribati", countryCode: "KI" },
//   { countryName: "Kuwait", countryCode: "KW" },
//   { countryName: "Kyrgyzstan", countryCode: "KG" },
//   { countryName: "Laos", countryCode: "LA" },
//   { countryName: "Latvia", countryCode: "LV" },
//   { countryName: "Lebanon", countryCode: "LB" },
//   { countryName: "Lesotho", countryCode: "LS" },
//   { countryName: "Liberia", countryCode: "LR" },
//   { countryName: "Libya", countryCode: "LY" },
//   { countryName: "Liechtenstein", countryCode: "LI" },
//   { countryName: "Lithuania", countryCode: "LT" },
//   { countryName: "Luxembourg", countryCode: "LU" },
//   { countryName: "Madagascar", countryCode: "MG" },
//   { countryName: "Malawi", countryCode: "MW" },
//   { countryName: "Malaysia", countryCode: "MY" },
//   { countryName: "Maldives", countryCode: "MV" },
//   { countryName: "Mali", countryCode: "ML" },
//   { countryName: "Malta", countryCode: "MT" },
//   { countryName: "Mauritania", countryCode: "MR" },
//   { countryName: "Mauritius", countryCode: "MU" },
//   { countryName: "Mexico", countryCode: "MX" },
//   { countryName: "Micronesia", countryCode: "FM" },
//   { countryName: "Moldova", countryCode: "MD" },
//   { countryName: "Monaco", countryCode: "MC" },
//   { countryName: "Mongolia", countryCode: "MN" },
//   { countryName: "Montenegro", countryCode: "ME" },
//   { countryName: "Morocco", countryCode: "MA" },
//   { countryName: "Mozambique", countryCode: "MZ" },
//   { countryName: "Myanmar", countryCode: "MM" },
//   { countryName: "Namibia", countryCode: "NA" },
//   { countryName: "Nauru", countryCode: "NR" },
//   { countryName: "Nepal", countryCode: "NP" },
//   { countryName: "Netherlands", countryCode: "NL" },
//   { countryName: "New Zealand", countryCode: "NZ" },
//   { countryName: "Nicaragua", countryCode: "NI" },
//   { countryName: "Niger", countryCode: "NE" },
//   { countryName: "Nigeria", countryCode: "NG" },
//   { countryName: "North Korea", countryCode: "KP" },
//   { countryName: "North Macedonia", countryCode: "MK" },
//   { countryName: "Norway", countryCode: "NO" },
//   { countryName: "Oman", countryCode: "OM" },
//   { countryName: "Pakistan", countryCode: "PK" },
//   { countryName: "Palau", countryCode: "PW" },
//   { countryName: "Palestine", countryCode: "PS" },
//   { countryName: "Panama", countryCode: "PA" },
//   { countryName: "Papua New Guinea", countryCode: "PG" },
//   { countryName: "Paraguay", countryCode: "PY" },
//   { countryName: "Peru", countryCode: "PE" },
//   { countryName: "Philippines", countryCode: "PH" },
//   { countryName: "Poland", countryCode: "PL" },
//   { countryName: "Portugal", countryCode: "PT" },
//   { countryName: "Qatar", countryCode: "QA" },
//   { countryName: "Romania", countryCode: "RO" },
//   { countryName: "Russia", countryCode: "RU" },
//   { countryName: "Rwanda", countryCode: "RW" },
//   { countryName: "Samoa", countryCode: "WS" },
//   { countryName: "San Marino", countryCode: "SM" },
//   { countryName: "Saudi Arabia", countryCode: "SA" },
//   { countryName: "Senegal", countryCode: "SN" },
//   { countryName: "Serbia", countryCode: "RS" },
//   { countryName: "Seychelles", countryCode: "SC" },
//   { countryName: "Sierra Leone", countryCode: "SL" },
//   { countryName: "Singapore", countryCode: "SG" },
//   { countryName: "Slovakia", countryCode: "SK" },
//   { countryName: "Slovenia", countryCode: "SI" },
//   { countryName: "Solomon Islands", countryCode: "SB" },
//   { countryName: "Somalia", countryCode: "SO" },
//   { countryName: "South Africa", countryCode: "ZA" },
//   { countryName: "South Korea", countryCode: "KR" },
//   { countryName: "South Sudan", countryCode: "SS" },
//   { countryName: "Spain", countryCode: "ES" },
//   { countryName: "Sri Lanka", countryCode: "LK" },
//   { countryName: "Sudan", countryCode: "SD" },
//   { countryName: "Suriname", countryCode: "SR" },
//   { countryName: "Sweden", countryCode: "SE" },
//   { countryName: "Switzerland", countryCode: "CH" },
//   { countryName: "Syria", countryCode: "SY" },
//   { countryName: "Taiwan", countryCode: "TW" },
//   { countryName: "Tajikistan", countryCode: "TJ" },
//   { countryName: "Tanzania", countryCode: "TZ" },
//   { countryName: "Thailand", countryCode: "TH" },
//   { countryName: "Timor-Leste", countryCode: "TL" },
//   { countryName: "Togo", countryCode: "TG" },
//   { countryName: "Tonga", countryCode: "TO" },
//   { countryName: "Trinidad and Tobago", countryCode: "TT" },
//   { countryName: "Tunisia", countryCode: "TN" },
//   { countryName: "Turkey", countryCode: "TR" },
//   { countryName: "Turkmenistan", countryCode: "TM" },
//   { countryName: "Tuvalu", countryCode: "TV" },
//   { countryName: "Uganda", countryCode: "UG" },
//   { countryName: "Ukraine", countryCode: "UA" },
//   { countryName: "United Arab Emirates", countryCode: "AE" },
//   { countryName: "United Kingdom", countryCode: "GB" },
//   { countryName: "United States", countryCode: "US" },
//   { countryName: "Uruguay", countryCode: "UY" },
//   { countryName: "Uzbekistan", countryCode: "UZ" },
//   { countryName: "Vanuatu", countryCode: "VU" },
//   { countryName: "Vatican City", countryCode: "VA" },
//   { countryName: "Venezuela", countryCode: "VE" },
//   { countryName: "Vietnam", countryCode: "VN" },
//   { countryName: "Yemen", countryCode: "YE" },
//   { countryName: "Zambia", countryCode: "ZM" },
//   { countryName: "Zimbabwe", countryCode: "ZW" },
// ];
