export const EventCategory = {
  MUSIC: "MUSIC",
  NIGHTLIFE: "NIGHTLIFE",
  WORKSHOP: "WORKSHOP",
  CONFERENCE: "CONFERENCE",
  EXHIBITION: "EXHIBITION",
  SPORTS: "SPORTS",
  FESTIVAL: "FESTIVAL",
  COMMUNITY: "COMMUNITY",
  OTHER: "OTHER",
} as const;
